// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package mocks

import "sync"

// FakeGitHubClient is a generated fake implementing pkg.GitHubClient.
type FakeGitHubClient struct {
	Method1Stub        func() error
	Method1Mutex       sync.Mutex
	Method1ArgsForCall []struct{}
	Method1Returns     struct{ Result1 error }
	Method1Invocations int

	Method2Stub        func() error
	Method2Mutex       sync.Mutex
	Method2ArgsForCall []struct{}
	Method2Returns     struct{ Result1 error }
	Method2Invocations int

	Method3Stub        func() error
	Method3Mutex       sync.Mutex
	Method3ArgsForCall []struct{}
	Method3Returns     struct{ Result1 error }
	Method3Invocations int

	Method4Stub        func() error
	Method4Mutex       sync.Mutex
	Method4ArgsForCall []struct{}
	Method4Returns     struct{ Result1 error }
	Method4Invocations int

	Method5Stub        func() error
	Method5Mutex       sync.Mutex
	Method5ArgsForCall []struct{}
	Method5Returns     struct{ Result1 error }
	Method5Invocations int

	Method6Stub        func() error
	Method6Mutex       sync.Mutex
	Method6ArgsForCall []struct{}
	Method6Returns     struct{ Result1 error }
	Method6Invocations int

	Method7Stub        func() error
	Method7Mutex       sync.Mutex
	Method7ArgsForCall []struct{}
	Method7Returns     struct{ Result1 error }
	Method7Invocations int

	Method8Stub        func() error
	Method8Mutex       sync.Mutex
	Method8ArgsForCall []struct{}
	Method8Returns     struct{ Result1 error }
	Method8Invocations int

	Method9Stub        func() error
	Method9Mutex       sync.Mutex
	Method9ArgsForCall []struct{}
	Method9Returns     struct{ Result1 error }
	Method9Invocations int

	Method10Stub        func() error
	Method10Mutex       sync.Mutex
	Method10ArgsForCall []struct{}
	Method10Returns     struct{ Result1 error }
	Method10Invocations int

	Method11Stub        func() error
	Method11Mutex       sync.Mutex
	Method11ArgsForCall []struct{}
	Method11Returns     struct{ Result1 error }
	Method11Invocations int

	Method12Stub        func() error
	Method12Mutex       sync.Mutex
	Method12ArgsForCall []struct{}
	Method12Returns     struct{ Result1 error }
	Method12Invocations int

	Method13Stub        func() error
	Method13Mutex       sync.Mutex
	Method13ArgsForCall []struct{}
	Method13Returns     struct{ Result1 error }
	Method13Invocations int

	Method14Stub        func() error
	Method14Mutex       sync.Mutex
	Method14ArgsForCall []struct{}
	Method14Returns     struct{ Result1 error }
	Method14Invocations int

	Method15Stub        func() error
	Method15Mutex       sync.Mutex
	Method15ArgsForCall []struct{}
	Method15Returns     struct{ Result1 error }
	Method15Invocations int

	Method16Stub        func() error
	Method16Mutex       sync.Mutex
	Method16ArgsForCall []struct{}
	Method16Returns     struct{ Result1 error }
	Method16Invocations int

	Method17Stub        func() error
	Method17Mutex       sync.Mutex
	Method17ArgsForCall []struct{}
	Method17Returns     struct{ Result1 error }
	Method17Invocations int

	Method18Stub        func() error
	Method18Mutex       sync.Mutex
	Method18ArgsForCall []struct{}
	Method18Returns     struct{ Result1 error }
	Method18Invocations int

	Method19Stub        func() error
	Method19Mutex       sync.Mutex
	Method19ArgsForCall []struct{}
	Method19Returns     struct{ Result1 error }
	Method19Invocations int

	Method20Stub        func() error
	Method20Mutex       sync.Mutex
	Method20ArgsForCall []struct{}
	Method20Returns     struct{ Result1 error }
	Method20Invocations int

	Method21Stub        func() error
	Method21Mutex       sync.Mutex
	Method21ArgsForCall []struct{}
	Method21Returns     struct{ Result1 error }
	Method21Invocations int

	Method22Stub        func() error
	Method22Mutex       sync.Mutex
	Method22ArgsForCall []struct{}
	Method22Returns     struct{ Result1 error }
	Method22Invocations int

	Method23Stub        func() error
	Method23Mutex       sync.Mutex
	Method23ArgsForCall []struct{}
	Method23Returns     struct{ Result1 error }
	Method23Invocations int

	Method24Stub        func() error
	Method24Mutex       sync.Mutex
	Method24ArgsForCall []struct{}
	Method24Returns     struct{ Result1 error }
	Method24Invocations int

	Method25Stub        func() error
	Method25Mutex       sync.Mutex
	Method25ArgsForCall []struct{}
	Method25Returns     struct{ Result1 error }
	Method25Invocations int

	Method26Stub        func() error
	Method26Mutex       sync.Mutex
	Method26ArgsForCall []struct{}
	Method26Returns     struct{ Result1 error }
	Method26Invocations int

	Method27Stub        func() error
	Method27Mutex       sync.Mutex
	Method27ArgsForCall []struct{}
	Method27Returns     struct{ Result1 error }
	Method27Invocations int

	Method28Stub        func() error
	Method28Mutex       sync.Mutex
	Method28ArgsForCall []struct{}
	Method28Returns     struct{ Result1 error }
	Method28Invocations int

	Method29Stub        func() error
	Method29Mutex       sync.Mutex
	Method29ArgsForCall []struct{}
	Method29Returns     struct{ Result1 error }
	Method29Invocations int

	Method30Stub        func() error
	Method30Mutex       sync.Mutex
	Method30ArgsForCall []struct{}
	Method30Returns     struct{ Result1 error }
	Method30Invocations int

}

func (fake *FakeGitHubClient) Method1() error {
	fake.Method1Mutex.Lock()
	defer fake.Method1Mutex.Unlock()
	fake.Method1Invocations++
	fake.Method1ArgsForCall = append(fake.Method1ArgsForCall, struct{}{})
	if fake.Method1Stub != nil {
		return fake.Method1Stub()
	}
	return fake.Method1Returns.Result1
}

func (fake *FakeGitHubClient) Method2() error {
	fake.Method2Mutex.Lock()
	defer fake.Method2Mutex.Unlock()
	fake.Method2Invocations++
	fake.Method2ArgsForCall = append(fake.Method2ArgsForCall, struct{}{})
	if fake.Method2Stub != nil {
		return fake.Method2Stub()
	}
	return fake.Method2Returns.Result1
}

func (fake *FakeGitHubClient) Method3() error {
	fake.Method3Mutex.Lock()
	defer fake.Method3Mutex.Unlock()
	fake.Method3Invocations++
	fake.Method3ArgsForCall = append(fake.Method3ArgsForCall, struct{}{})
	if fake.Method3Stub != nil {
		return fake.Method3Stub()
	}
	return fake.Method3Returns.Result1
}

func (fake *FakeGitHubClient) Method4() error {
	fake.Method4Mutex.Lock()
	defer fake.Method4Mutex.Unlock()
	fake.Method4Invocations++
	fake.Method4ArgsForCall = append(fake.Method4ArgsForCall, struct{}{})
	if fake.Method4Stub != nil {
		return fake.Method4Stub()
	}
	return fake.Method4Returns.Result1
}

func (fake *FakeGitHubClient) Method5() error {
	fake.Method5Mutex.Lock()
	defer fake.Method5Mutex.Unlock()
	fake.Method5Invocations++
	fake.Method5ArgsForCall = append(fake.Method5ArgsForCall, struct{}{})
	if fake.Method5Stub != nil {
		return fake.Method5Stub()
	}
	return fake.Method5Returns.Result1
}

func (fake *FakeGitHubClient) Method6() error {
	fake.Method6Mutex.Lock()
	defer fake.Method6Mutex.Unlock()
	fake.Method6Invocations++
	fake.Method6ArgsForCall = append(fake.Method6ArgsForCall, struct{}{})
	if fake.Method6Stub != nil {
		return fake.Method6Stub()
	}
	return fake.Method6Returns.Result1
}

func (fake *FakeGitHubClient) Method7() error {
	fake.Method7Mutex.Lock()
	defer fake.Method7Mutex.Unlock()
	fake.Method7Invocations++
	fake.Method7ArgsForCall = append(fake.Method7ArgsForCall, struct{}{})
	if fake.Method7Stub != nil {
		return fake.Method7Stub()
	}
	return fake.Method7Returns.Result1
}

func (fake *FakeGitHubClient) Method8() error {
	fake.Method8Mutex.Lock()
	defer fake.Method8Mutex.Unlock()
	fake.Method8Invocations++
	fake.Method8ArgsForCall = append(fake.Method8ArgsForCall, struct{}{})
	if fake.Method8Stub != nil {
		return fake.Method8Stub()
	}
	return fake.Method8Returns.Result1
}

func (fake *FakeGitHubClient) Method9() error {
	fake.Method9Mutex.Lock()
	defer fake.Method9Mutex.Unlock()
	fake.Method9Invocations++
	fake.Method9ArgsForCall = append(fake.Method9ArgsForCall, struct{}{})
	if fake.Method9Stub != nil {
		return fake.Method9Stub()
	}
	return fake.Method9Returns.Result1
}

func (fake *FakeGitHubClient) Method10() error {
	fake.Method10Mutex.Lock()
	defer fake.Method10Mutex.Unlock()
	fake.Method10Invocations++
	fake.Method10ArgsForCall = append(fake.Method10ArgsForCall, struct{}{})
	if fake.Method10Stub != nil {
		return fake.Method10Stub()
	}
	return fake.Method10Returns.Result1
}

func (fake *FakeGitHubClient) Method11() error {
	fake.Method11Mutex.Lock()
	defer fake.Method11Mutex.Unlock()
	fake.Method11Invocations++
	fake.Method11ArgsForCall = append(fake.Method11ArgsForCall, struct{}{})
	if fake.Method11Stub != nil {
		return fake.Method11Stub()
	}
	return fake.Method11Returns.Result1
}

func (fake *FakeGitHubClient) Method12() error {
	fake.Method12Mutex.Lock()
	defer fake.Method12Mutex.Unlock()
	fake.Method12Invocations++
	fake.Method12ArgsForCall = append(fake.Method12ArgsForCall, struct{}{})
	if fake.Method12Stub != nil {
		return fake.Method12Stub()
	}
	return fake.Method12Returns.Result1
}

func (fake *FakeGitHubClient) Method13() error {
	fake.Method13Mutex.Lock()
	defer fake.Method13Mutex.Unlock()
	fake.Method13Invocations++
	fake.Method13ArgsForCall = append(fake.Method13ArgsForCall, struct{}{})
	if fake.Method13Stub != nil {
		return fake.Method13Stub()
	}
	return fake.Method13Returns.Result1
}

func (fake *FakeGitHubClient) Method14() error {
	fake.Method14Mutex.Lock()
	defer fake.Method14Mutex.Unlock()
	fake.Method14Invocations++
	fake.Method14ArgsForCall = append(fake.Method14ArgsForCall, struct{}{})
	if fake.Method14Stub != nil {
		return fake.Method14Stub()
	}
	return fake.Method14Returns.Result1
}

func (fake *FakeGitHubClient) Method15() error {
	fake.Method15Mutex.Lock()
	defer fake.Method15Mutex.Unlock()
	fake.Method15Invocations++
	fake.Method15ArgsForCall = append(fake.Method15ArgsForCall, struct{}{})
	if fake.Method15Stub != nil {
		return fake.Method15Stub()
	}
	return fake.Method15Returns.Result1
}

func (fake *FakeGitHubClient) Method16() error {
	fake.Method16Mutex.Lock()
	defer fake.Method16Mutex.Unlock()
	fake.Method16Invocations++
	fake.Method16ArgsForCall = append(fake.Method16ArgsForCall, struct{}{})
	if fake.Method16Stub != nil {
		return fake.Method16Stub()
	}
	return fake.Method16Returns.Result1
}

func (fake *FakeGitHubClient) Method17() error {
	fake.Method17Mutex.Lock()
	defer fake.Method17Mutex.Unlock()
	fake.Method17Invocations++
	fake.Method17ArgsForCall = append(fake.Method17ArgsForCall, struct{}{})
	if fake.Method17Stub != nil {
		return fake.Method17Stub()
	}
	return fake.Method17Returns.Result1
}

func (fake *FakeGitHubClient) Method18() error {
	fake.Method18Mutex.Lock()
	defer fake.Method18Mutex.Unlock()
	fake.Method18Invocations++
	fake.Method18ArgsForCall = append(fake.Method18ArgsForCall, struct{}{})
	if fake.Method18Stub != nil {
		return fake.Method18Stub()
	}
	return fake.Method18Returns.Result1
}

func (fake *FakeGitHubClient) Method19() error {
	fake.Method19Mutex.Lock()
	defer fake.Method19Mutex.Unlock()
	fake.Method19Invocations++
	fake.Method19ArgsForCall = append(fake.Method19ArgsForCall, struct{}{})
	if fake.Method19Stub != nil {
		return fake.Method19Stub()
	}
	return fake.Method19Returns.Result1
}

func (fake *FakeGitHubClient) Method20() error {
	fake.Method20Mutex.Lock()
	defer fake.Method20Mutex.Unlock()
	fake.Method20Invocations++
	fake.Method20ArgsForCall = append(fake.Method20ArgsForCall, struct{}{})
	if fake.Method20Stub != nil {
		return fake.Method20Stub()
	}
	return fake.Method20Returns.Result1
}

func (fake *FakeGitHubClient) Method21() error {
	fake.Method21Mutex.Lock()
	defer fake.Method21Mutex.Unlock()
	fake.Method21Invocations++
	fake.Method21ArgsForCall = append(fake.Method21ArgsForCall, struct{}{})
	if fake.Method21Stub != nil {
		return fake.Method21Stub()
	}
	return fake.Method21Returns.Result1
}

func (fake *FakeGitHubClient) Method22() error {
	fake.Method22Mutex.Lock()
	defer fake.Method22Mutex.Unlock()
	fake.Method22Invocations++
	fake.Method22ArgsForCall = append(fake.Method22ArgsForCall, struct{}{})
	if fake.Method22Stub != nil {
		return fake.Method22Stub()
	}
	return fake.Method22Returns.Result1
}

func (fake *FakeGitHubClient) Method23() error {
	fake.Method23Mutex.Lock()
	defer fake.Method23Mutex.Unlock()
	fake.Method23Invocations++
	fake.Method23ArgsForCall = append(fake.Method23ArgsForCall, struct{}{})
	if fake.Method23Stub != nil {
		return fake.Method23Stub()
	}
	return fake.Method23Returns.Result1
}

func (fake *FakeGitHubClient) Method24() error {
	fake.Method24Mutex.Lock()
	defer fake.Method24Mutex.Unlock()
	fake.Method24Invocations++
	fake.Method24ArgsForCall = append(fake.Method24ArgsForCall, struct{}{})
	if fake.Method24Stub != nil {
		return fake.Method24Stub()
	}
	return fake.Method24Returns.Result1
}

func (fake *FakeGitHubClient) Method25() error {
	fake.Method25Mutex.Lock()
	defer fake.Method25Mutex.Unlock()
	fake.Method25Invocations++
	fake.Method25ArgsForCall = append(fake.Method25ArgsForCall, struct{}{})
	if fake.Method25Stub != nil {
		return fake.Method25Stub()
	}
	return fake.Method25Returns.Result1
}

func (fake *FakeGitHubClient) Method26() error {
	fake.Method26Mutex.Lock()
	defer fake.Method26Mutex.Unlock()
	fake.Method26Invocations++
	fake.Method26ArgsForCall = append(fake.Method26ArgsForCall, struct{}{})
	if fake.Method26Stub != nil {
		return fake.Method26Stub()
	}
	return fake.Method26Returns.Result1
}

func (fake *FakeGitHubClient) Method27() error {
	fake.Method27Mutex.Lock()
	defer fake.Method27Mutex.Unlock()
	fake.Method27Invocations++
	fake.Method27ArgsForCall = append(fake.Method27ArgsForCall, struct{}{})
	if fake.Method27Stub != nil {
		return fake.Method27Stub()
	}
	return fake.Method27Returns.Result1
}

func (fake *FakeGitHubClient) Method28() error {
	fake.Method28Mutex.Lock()
	defer fake.Method28Mutex.Unlock()
	fake.Method28Invocations++
	fake.Method28ArgsForCall = append(fake.Method28ArgsForCall, struct{}{})
	if fake.Method28Stub != nil {
		return fake.Method28Stub()
	}
	return fake.Method28Returns.Result1
}

func (fake *FakeGitHubClient) Method29() error {
	fake.Method29Mutex.Lock()
	defer fake.Method29Mutex.Unlock()
	fake.Method29Invocations++
	fake.Method29ArgsForCall = append(fake.Method29ArgsForCall, struct{}{})
	if fake.Method29Stub != nil {
		return fake.Method29Stub()
	}
	return fake.Method29Returns.Result1
}

func (fake *FakeGitHubClient) Method30() error {
	fake.Method30Mutex.Lock()
	defer fake.Method30Mutex.Unlock()
	fake.Method30Invocations++
	fake.Method30ArgsForCall = append(fake.Method30ArgsForCall, struct{}{})
	if fake.Method30Stub != nil {
		return fake.Method30Stub()
	}
	return fake.Method30Returns.Result1
}

func (fake *FakeGitHubClient) MethodInvocations() map[string]int {
	return map[string]int{
		"Method1": fake.Method1Invocations,
		"Method2": fake.Method2Invocations,
		"Method3": fake.Method3Invocations,
		"Method4": fake.Method4Invocations,
		"Method5": fake.Method5Invocations,
		"Method6": fake.Method6Invocations,
		"Method7": fake.Method7Invocations,
		"Method8": fake.Method8Invocations,
		"Method9": fake.Method9Invocations,
		"Method10": fake.Method10Invocations,
		"Method11": fake.Method11Invocations,
		"Method12": fake.Method12Invocations,
		"Method13": fake.Method13Invocations,
		"Method14": fake.Method14Invocations,
		"Method15": fake.Method15Invocations,
		"Method16": fake.Method16Invocations,
		"Method17": fake.Method17Invocations,
		"Method18": fake.Method18Invocations,
		"Method19": fake.Method19Invocations,
		"Method20": fake.Method20Invocations,
		"Method21": fake.Method21Invocations,
		"Method22": fake.Method22Invocations,
		"Method23": fake.Method23Invocations,
		"Method24": fake.Method24Invocations,
		"Method25": fake.Method25Invocations,
		"Method26": fake.Method26Invocations,
		"Method27": fake.Method27Invocations,
		"Method28": fake.Method28Invocations,
		"Method29": fake.Method29Invocations,
		"Method30": fake.Method30Invocations,
	}
}
