// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-pr-watcher/pkg"
	"github.com/bborbe/maintainer/maintainerconfig"
	"github.com/bborbe/time"
)

type GitHubClient struct {
	AddLabelStub        func(context.Context, string, string, int, string) error
	addLabelMutex       sync.RWMutex
	addLabelArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}
	addLabelReturns struct {
		result1 error
	}
	addLabelReturnsOnCall map[int]struct {
		result1 error
	}
	EnableAutoMergeStub        func(context.Context, string, string, int) error
	enableAutoMergeMutex       sync.RWMutex
	enableAutoMergeArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}
	enableAutoMergeReturns struct {
		result1 error
	}
	enableAutoMergeReturnsOnCall map[int]struct {
		result1 error
	}
	GetMaintainerConfigStub        func(context.Context, string, string) (maintainerconfig.MaintainerConfig, error)
	getMaintainerConfigMutex       sync.RWMutex
	getMaintainerConfigArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	getMaintainerConfigReturns struct {
		result1 maintainerconfig.MaintainerConfig
		result2 error
	}
	getMaintainerConfigReturnsOnCall map[int]struct {
		result1 maintainerconfig.MaintainerConfig
		result2 error
	}
	GetPRDetailsStub        func(context.Context, string, string, int) (pkg.PRDetails, error)
	getPRDetailsMutex       sync.RWMutex
	getPRDetailsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}
	getPRDetailsReturns struct {
		result1 pkg.PRDetails
		result2 error
	}
	getPRDetailsReturnsOnCall map[int]struct {
		result1 pkg.PRDetails
		result2 error
	}
	GetRateLimitCoreRemainingStub        func(context.Context) (int, error)
	getRateLimitCoreRemainingMutex       sync.RWMutex
	getRateLimitCoreRemainingArgsForCall []struct {
		arg1 context.Context
	}
	getRateLimitCoreRemainingReturns struct {
		result1 int
		result2 error
	}
	getRateLimitCoreRemainingReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	ListPRFilesStub        func(context.Context, string, string, int) ([]pkg.PRFile, error)
	listPRFilesMutex       sync.RWMutex
	listPRFilesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}
	listPRFilesReturns struct {
		result1 []pkg.PRFile
		result2 error
	}
	listPRFilesReturnsOnCall map[int]struct {
		result1 []pkg.PRFile
		result2 error
	}
	RateLimitRemainingStub        func() int
	rateLimitRemainingMutex       sync.RWMutex
	rateLimitRemainingArgsForCall []struct {
	}
	rateLimitRemainingReturns struct {
		result1 int
	}
	rateLimitRemainingReturnsOnCall map[int]struct {
		result1 int
	}
	SearchPRsStub        func(context.Context, string, time.DateTime, int) (pkg.SearchResult, error)
	searchPRsMutex       sync.RWMutex
	searchPRsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 time.DateTime
		arg4 int
	}
	searchPRsReturns struct {
		result1 pkg.SearchResult
		result2 error
	}
	searchPRsReturnsOnCall map[int]struct {
		result1 pkg.SearchResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GitHubClient) AddLabel(arg1 context.Context, arg2 string, arg3 string, arg4 int, arg5 string) error {
	fake.addLabelMutex.Lock()
	ret, specificReturn := fake.addLabelReturnsOnCall[len(fake.addLabelArgsForCall)]
	fake.addLabelArgsForCall = append(fake.addLabelArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.AddLabelStub
	fakeReturns := fake.addLabelReturns
	fake.recordInvocation("AddLabel", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.addLabelMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitHubClient) AddLabelCallCount() int {
	fake.addLabelMutex.RLock()
	defer fake.addLabelMutex.RUnlock()
	return len(fake.addLabelArgsForCall)
}

func (fake *GitHubClient) AddLabelCalls(stub func(context.Context, string, string, int, string) error) {
	fake.addLabelMutex.Lock()
	defer fake.addLabelMutex.Unlock()
	fake.AddLabelStub = stub
}

func (fake *GitHubClient) AddLabelArgsForCall(i int) (context.Context, string, string, int, string) {
	fake.addLabelMutex.RLock()
	defer fake.addLabelMutex.RUnlock()
	argsForCall := fake.addLabelArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *GitHubClient) AddLabelReturns(result1 error) {
	fake.addLabelMutex.Lock()
	defer fake.addLabelMutex.Unlock()
	fake.AddLabelStub = nil
	fake.addLabelReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitHubClient) AddLabelReturnsOnCall(i int, result1 error) {
	fake.addLabelMutex.Lock()
	defer fake.addLabelMutex.Unlock()
	fake.AddLabelStub = nil
	if fake.addLabelReturnsOnCall == nil {
		fake.addLabelReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addLabelReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitHubClient) EnableAutoMerge(arg1 context.Context, arg2 string, arg3 string, arg4 int) error {
	fake.enableAutoMergeMutex.Lock()
	ret, specificReturn := fake.enableAutoMergeReturnsOnCall[len(fake.enableAutoMergeArgsForCall)]
	fake.enableAutoMergeArgsForCall = append(fake.enableAutoMergeArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.EnableAutoMergeStub
	fakeReturns := fake.enableAutoMergeReturns
	fake.recordInvocation("EnableAutoMerge", []interface{}{arg1, arg2, arg3, arg4})
	fake.enableAutoMergeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitHubClient) EnableAutoMergeCallCount() int {
	fake.enableAutoMergeMutex.RLock()
	defer fake.enableAutoMergeMutex.RUnlock()
	return len(fake.enableAutoMergeArgsForCall)
}

func (fake *GitHubClient) EnableAutoMergeCalls(stub func(context.Context, string, string, int) error) {
	fake.enableAutoMergeMutex.Lock()
	defer fake.enableAutoMergeMutex.Unlock()
	fake.EnableAutoMergeStub = stub
}

func (fake *GitHubClient) EnableAutoMergeArgsForCall(i int) (context.Context, string, string, int) {
	fake.enableAutoMergeMutex.RLock()
	defer fake.enableAutoMergeMutex.RUnlock()
	argsForCall := fake.enableAutoMergeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitHubClient) EnableAutoMergeReturns(result1 error) {
	fake.enableAutoMergeMutex.Lock()
	defer fake.enableAutoMergeMutex.Unlock()
	fake.EnableAutoMergeStub = nil
	fake.enableAutoMergeReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitHubClient) EnableAutoMergeReturnsOnCall(i int, result1 error) {
	fake.enableAutoMergeMutex.Lock()
	defer fake.enableAutoMergeMutex.Unlock()
	fake.EnableAutoMergeStub = nil
	if fake.enableAutoMergeReturnsOnCall == nil {
		fake.enableAutoMergeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.enableAutoMergeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitHubClient) GetMaintainerConfig(arg1 context.Context, arg2 string, arg3 string) (maintainerconfig.MaintainerConfig, error) {
	fake.getMaintainerConfigMutex.Lock()
	ret, specificReturn := fake.getMaintainerConfigReturnsOnCall[len(fake.getMaintainerConfigArgsForCall)]
	fake.getMaintainerConfigArgsForCall = append(fake.getMaintainerConfigArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetMaintainerConfigStub
	fakeReturns := fake.getMaintainerConfigReturns
	fake.recordInvocation("GetMaintainerConfig", []interface{}{arg1, arg2, arg3})
	fake.getMaintainerConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetMaintainerConfigCallCount() int {
	fake.getMaintainerConfigMutex.RLock()
	defer fake.getMaintainerConfigMutex.RUnlock()
	return len(fake.getMaintainerConfigArgsForCall)
}

func (fake *GitHubClient) GetMaintainerConfigCalls(stub func(context.Context, string, string) (maintainerconfig.MaintainerConfig, error)) {
	fake.getMaintainerConfigMutex.Lock()
	defer fake.getMaintainerConfigMutex.Unlock()
	fake.GetMaintainerConfigStub = stub
}

func (fake *GitHubClient) GetMaintainerConfigArgsForCall(i int) (context.Context, string, string) {
	fake.getMaintainerConfigMutex.RLock()
	defer fake.getMaintainerConfigMutex.RUnlock()
	argsForCall := fake.getMaintainerConfigArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *GitHubClient) GetMaintainerConfigReturns(result1 maintainerconfig.MaintainerConfig, result2 error) {
	fake.getMaintainerConfigMutex.Lock()
	defer fake.getMaintainerConfigMutex.Unlock()
	fake.GetMaintainerConfigStub = nil
	fake.getMaintainerConfigReturns = struct {
		result1 maintainerconfig.MaintainerConfig
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetMaintainerConfigReturnsOnCall(i int, result1 maintainerconfig.MaintainerConfig, result2 error) {
	fake.getMaintainerConfigMutex.Lock()
	defer fake.getMaintainerConfigMutex.Unlock()
	fake.GetMaintainerConfigStub = nil
	if fake.getMaintainerConfigReturnsOnCall == nil {
		fake.getMaintainerConfigReturnsOnCall = make(map[int]struct {
			result1 maintainerconfig.MaintainerConfig
			result2 error
		})
	}
	fake.getMaintainerConfigReturnsOnCall[i] = struct {
		result1 maintainerconfig.MaintainerConfig
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetPRDetails(arg1 context.Context, arg2 string, arg3 string, arg4 int) (pkg.PRDetails, error) {
	fake.getPRDetailsMutex.Lock()
	ret, specificReturn := fake.getPRDetailsReturnsOnCall[len(fake.getPRDetailsArgsForCall)]
	fake.getPRDetailsArgsForCall = append(fake.getPRDetailsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetPRDetailsStub
	fakeReturns := fake.getPRDetailsReturns
	fake.recordInvocation("GetPRDetails", []interface{}{arg1, arg2, arg3, arg4})
	fake.getPRDetailsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetPRDetailsCallCount() int {
	fake.getPRDetailsMutex.RLock()
	defer fake.getPRDetailsMutex.RUnlock()
	return len(fake.getPRDetailsArgsForCall)
}

func (fake *GitHubClient) GetPRDetailsCalls(stub func(context.Context, string, string, int) (pkg.PRDetails, error)) {
	fake.getPRDetailsMutex.Lock()
	defer fake.getPRDetailsMutex.Unlock()
	fake.GetPRDetailsStub = stub
}

func (fake *GitHubClient) GetPRDetailsArgsForCall(i int) (context.Context, string, string, int) {
	fake.getPRDetailsMutex.RLock()
	defer fake.getPRDetailsMutex.RUnlock()
	argsForCall := fake.getPRDetailsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitHubClient) GetPRDetailsReturns(result1 pkg.PRDetails, result2 error) {
	fake.getPRDetailsMutex.Lock()
	defer fake.getPRDetailsMutex.Unlock()
	fake.GetPRDetailsStub = nil
	fake.getPRDetailsReturns = struct {
		result1 pkg.PRDetails
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetPRDetailsReturnsOnCall(i int, result1 pkg.PRDetails, result2 error) {
	fake.getPRDetailsMutex.Lock()
	defer fake.getPRDetailsMutex.Unlock()
	fake.GetPRDetailsStub = nil
	if fake.getPRDetailsReturnsOnCall == nil {
		fake.getPRDetailsReturnsOnCall = make(map[int]struct {
			result1 pkg.PRDetails
			result2 error
		})
	}
	fake.getPRDetailsReturnsOnCall[i] = struct {
		result1 pkg.PRDetails
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetRateLimitCoreRemaining(arg1 context.Context) (int, error) {
	fake.getRateLimitCoreRemainingMutex.Lock()
	ret, specificReturn := fake.getRateLimitCoreRemainingReturnsOnCall[len(fake.getRateLimitCoreRemainingArgsForCall)]
	fake.getRateLimitCoreRemainingArgsForCall = append(fake.getRateLimitCoreRemainingArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetRateLimitCoreRemainingStub
	fakeReturns := fake.getRateLimitCoreRemainingReturns
	fake.recordInvocation("GetRateLimitCoreRemaining", []interface{}{arg1})
	fake.getRateLimitCoreRemainingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetRateLimitCoreRemainingCallCount() int {
	fake.getRateLimitCoreRemainingMutex.RLock()
	defer fake.getRateLimitCoreRemainingMutex.RUnlock()
	return len(fake.getRateLimitCoreRemainingArgsForCall)
}

func (fake *GitHubClient) GetRateLimitCoreRemainingCalls(stub func(context.Context) (int, error)) {
	fake.getRateLimitCoreRemainingMutex.Lock()
	defer fake.getRateLimitCoreRemainingMutex.Unlock()
	fake.GetRateLimitCoreRemainingStub = stub
}

func (fake *GitHubClient) GetRateLimitCoreRemainingArgsForCall(i int) context.Context {
	fake.getRateLimitCoreRemainingMutex.RLock()
	defer fake.getRateLimitCoreRemainingMutex.RUnlock()
	argsForCall := fake.getRateLimitCoreRemainingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *GitHubClient) GetRateLimitCoreRemainingReturns(result1 int, result2 error) {
	fake.getRateLimitCoreRemainingMutex.Lock()
	defer fake.getRateLimitCoreRemainingMutex.Unlock()
	fake.GetRateLimitCoreRemainingStub = nil
	fake.getRateLimitCoreRemainingReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetRateLimitCoreRemainingReturnsOnCall(i int, result1 int, result2 error) {
	fake.getRateLimitCoreRemainingMutex.Lock()
	defer fake.getRateLimitCoreRemainingMutex.Unlock()
	fake.GetRateLimitCoreRemainingStub = nil
	if fake.getRateLimitCoreRemainingReturnsOnCall == nil {
		fake.getRateLimitCoreRemainingReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.getRateLimitCoreRemainingReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) ListPRFiles(arg1 context.Context, arg2 string, arg3 string, arg4 int) ([]pkg.PRFile, error) {
	fake.listPRFilesMutex.Lock()
	ret, specificReturn := fake.listPRFilesReturnsOnCall[len(fake.listPRFilesArgsForCall)]
	fake.listPRFilesArgsForCall = append(fake.listPRFilesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListPRFilesStub
	fakeReturns := fake.listPRFilesReturns
	fake.recordInvocation("ListPRFiles", []interface{}{arg1, arg2, arg3, arg4})
	fake.listPRFilesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) ListPRFilesCallCount() int {
	fake.listPRFilesMutex.RLock()
	defer fake.listPRFilesMutex.RUnlock()
	return len(fake.listPRFilesArgsForCall)
}

func (fake *GitHubClient) ListPRFilesCalls(stub func(context.Context, string, string, int) ([]pkg.PRFile, error)) {
	fake.listPRFilesMutex.Lock()
	defer fake.listPRFilesMutex.Unlock()
	fake.ListPRFilesStub = stub
}

func (fake *GitHubClient) ListPRFilesArgsForCall(i int) (context.Context, string, string, int) {
	fake.listPRFilesMutex.RLock()
	defer fake.listPRFilesMutex.RUnlock()
	argsForCall := fake.listPRFilesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitHubClient) ListPRFilesReturns(result1 []pkg.PRFile, result2 error) {
	fake.listPRFilesMutex.Lock()
	defer fake.listPRFilesMutex.Unlock()
	fake.ListPRFilesStub = nil
	fake.listPRFilesReturns = struct {
		result1 []pkg.PRFile
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) ListPRFilesReturnsOnCall(i int, result1 []pkg.PRFile, result2 error) {
	fake.listPRFilesMutex.Lock()
	defer fake.listPRFilesMutex.Unlock()
	fake.ListPRFilesStub = nil
	if fake.listPRFilesReturnsOnCall == nil {
		fake.listPRFilesReturnsOnCall = make(map[int]struct {
			result1 []pkg.PRFile
			result2 error
		})
	}
	fake.listPRFilesReturnsOnCall[i] = struct {
		result1 []pkg.PRFile
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) RateLimitRemaining() int {
	fake.rateLimitRemainingMutex.Lock()
	ret, specificReturn := fake.rateLimitRemainingReturnsOnCall[len(fake.rateLimitRemainingArgsForCall)]
	fake.rateLimitRemainingArgsForCall = append(fake.rateLimitRemainingArgsForCall, struct {
	}{})
	stub := fake.RateLimitRemainingStub
	fakeReturns := fake.rateLimitRemainingReturns
	fake.recordInvocation("RateLimitRemaining", []interface{}{})
	fake.rateLimitRemainingMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitHubClient) RateLimitRemainingCallCount() int {
	fake.rateLimitRemainingMutex.RLock()
	defer fake.rateLimitRemainingMutex.RUnlock()
	return len(fake.rateLimitRemainingArgsForCall)
}

func (fake *GitHubClient) RateLimitRemainingCalls(stub func() int) {
	fake.rateLimitRemainingMutex.Lock()
	defer fake.rateLimitRemainingMutex.Unlock()
	fake.RateLimitRemainingStub = stub
}

func (fake *GitHubClient) RateLimitRemainingReturns(result1 int) {
	fake.rateLimitRemainingMutex.Lock()
	defer fake.rateLimitRemainingMutex.Unlock()
	fake.RateLimitRemainingStub = nil
	fake.rateLimitRemainingReturns = struct {
		result1 int
	}{result1}
}

func (fake *GitHubClient) RateLimitRemainingReturnsOnCall(i int, result1 int) {
	fake.rateLimitRemainingMutex.Lock()
	defer fake.rateLimitRemainingMutex.Unlock()
	fake.RateLimitRemainingStub = nil
	if fake.rateLimitRemainingReturnsOnCall == nil {
		fake.rateLimitRemainingReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.rateLimitRemainingReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *GitHubClient) SearchPRs(arg1 context.Context, arg2 string, arg3 time.DateTime, arg4 int) (pkg.SearchResult, error) {
	fake.searchPRsMutex.Lock()
	ret, specificReturn := fake.searchPRsReturnsOnCall[len(fake.searchPRsArgsForCall)]
	fake.searchPRsArgsForCall = append(fake.searchPRsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 time.DateTime
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.SearchPRsStub
	fakeReturns := fake.searchPRsReturns
	fake.recordInvocation("SearchPRs", []interface{}{arg1, arg2, arg3, arg4})
	fake.searchPRsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) SearchPRsCallCount() int {
	fake.searchPRsMutex.RLock()
	defer fake.searchPRsMutex.RUnlock()
	return len(fake.searchPRsArgsForCall)
}

func (fake *GitHubClient) SearchPRsCalls(stub func(context.Context, string, time.DateTime, int) (pkg.SearchResult, error)) {
	fake.searchPRsMutex.Lock()
	defer fake.searchPRsMutex.Unlock()
	fake.SearchPRsStub = stub
}

func (fake *GitHubClient) SearchPRsArgsForCall(i int) (context.Context, string, time.DateTime, int) {
	fake.searchPRsMutex.RLock()
	defer fake.searchPRsMutex.RUnlock()
	argsForCall := fake.searchPRsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitHubClient) SearchPRsReturns(result1 pkg.SearchResult, result2 error) {
	fake.searchPRsMutex.Lock()
	defer fake.searchPRsMutex.Unlock()
	fake.SearchPRsStub = nil
	fake.searchPRsReturns = struct {
		result1 pkg.SearchResult
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) SearchPRsReturnsOnCall(i int, result1 pkg.SearchResult, result2 error) {
	fake.searchPRsMutex.Lock()
	defer fake.searchPRsMutex.Unlock()
	fake.SearchPRsStub = nil
	if fake.searchPRsReturnsOnCall == nil {
		fake.searchPRsReturnsOnCall = make(map[int]struct {
			result1 pkg.SearchResult
			result2 error
		})
	}
	fake.searchPRsReturnsOnCall[i] = struct {
		result1 pkg.SearchResult
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GitHubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.GitHubClient = new(GitHubClient)
