// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"sync"

	"github.com/bborbe/github-pr-watcher/pkg/reviewignore"
)

type ReviewIgnoreMatcher struct {
	EmptyStub        func() bool
	emptyMutex       sync.RWMutex
	emptyArgsForCall []struct {
	}
	emptyReturns struct {
		result1 bool
	}
	emptyReturnsOnCall map[int]struct {
		result1 bool
	}
	MatchStub        func(string) bool
	matchMutex       sync.RWMutex
	matchArgsForCall []struct {
		arg1 string
	}
	matchReturns struct {
		result1 bool
	}
	matchReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ReviewIgnoreMatcher) Empty() bool {
	fake.emptyMutex.Lock()
	ret, specificReturn := fake.emptyReturnsOnCall[len(fake.emptyArgsForCall)]
	fake.emptyArgsForCall = append(fake.emptyArgsForCall, struct {
	}{})
	stub := fake.EmptyStub
	fakeReturns := fake.emptyReturns
	fake.recordInvocation("Empty", []interface{}{})
	fake.emptyMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ReviewIgnoreMatcher) EmptyCallCount() int {
	fake.emptyMutex.RLock()
	defer fake.emptyMutex.RUnlock()
	return len(fake.emptyArgsForCall)
}

func (fake *ReviewIgnoreMatcher) EmptyCalls(stub func() bool) {
	fake.emptyMutex.Lock()
	defer fake.emptyMutex.Unlock()
	fake.EmptyStub = stub
}

func (fake *ReviewIgnoreMatcher) EmptyReturns(result1 bool) {
	fake.emptyMutex.Lock()
	defer fake.emptyMutex.Unlock()
	fake.EmptyStub = nil
	fake.emptyReturns = struct {
		result1 bool
	}{result1}
}

func (fake *ReviewIgnoreMatcher) EmptyReturnsOnCall(i int, result1 bool) {
	fake.emptyMutex.Lock()
	defer fake.emptyMutex.Unlock()
	fake.EmptyStub = nil
	if fake.emptyReturnsOnCall == nil {
		fake.emptyReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.emptyReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *ReviewIgnoreMatcher) Match(arg1 string) bool {
	fake.matchMutex.Lock()
	ret, specificReturn := fake.matchReturnsOnCall[len(fake.matchArgsForCall)]
	fake.matchArgsForCall = append(fake.matchArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.MatchStub
	fakeReturns := fake.matchReturns
	fake.recordInvocation("Match", []interface{}{arg1})
	fake.matchMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ReviewIgnoreMatcher) MatchCallCount() int {
	fake.matchMutex.RLock()
	defer fake.matchMutex.RUnlock()
	return len(fake.matchArgsForCall)
}

func (fake *ReviewIgnoreMatcher) MatchCalls(stub func(string) bool) {
	fake.matchMutex.Lock()
	defer fake.matchMutex.Unlock()
	fake.MatchStub = stub
}

func (fake *ReviewIgnoreMatcher) MatchArgsForCall(i int) string {
	fake.matchMutex.RLock()
	defer fake.matchMutex.RUnlock()
	argsForCall := fake.matchArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ReviewIgnoreMatcher) MatchReturns(result1 bool) {
	fake.matchMutex.Lock()
	defer fake.matchMutex.Unlock()
	fake.MatchStub = nil
	fake.matchReturns = struct {
		result1 bool
	}{result1}
}

func (fake *ReviewIgnoreMatcher) MatchReturnsOnCall(i int, result1 bool) {
	fake.matchMutex.Lock()
	defer fake.matchMutex.Unlock()
	fake.MatchStub = nil
	if fake.matchReturnsOnCall == nil {
		fake.matchReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.matchReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *ReviewIgnoreMatcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ReviewIgnoreMatcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ reviewignore.Matcher = new(ReviewIgnoreMatcher)
